import { SignJWT, jwtVerify } from "jose";

const SESSION_COOKIE = "ws_session";
const SESSION_TTL_SEC = 60 * 60 * 24 * 30;
const MIN_SECRET_LEN = 32;
const MIN_UNIQUE_CHARS = 8;
const ISSUER = "workspace-app";
const AUDIENCE = "workspace-session";

function secretKey(): Uint8Array {
  const raw = process.env.SESSION_SECRET;
  if (!raw || raw.length < MIN_SECRET_LEN) {
    throw new Error(
      `SESSION_SECRET must be at least ${MIN_SECRET_LEN} chars (use 64-char hex from crypto.randomBytes(32))`,
    );
  }
  const unique = new Set(raw).size;
  if (unique < MIN_UNIQUE_CHARS) {
    throw new Error(
      `SESSION_SECRET has too low entropy (only ${unique} unique chars); use randomly generated bytes`,
    );
  }
  return new TextEncoder().encode(raw);
}

let cachedKey: Uint8Array | null = null;
function getKey(): Uint8Array {
  if (!cachedKey) cachedKey = secretKey();
  return cachedKey;
}

export function assertSessionSecretConfigured(): void {
  getKey();
}

export type SessionPayload = {
  mid: string;
  gid: string;
  sec: string;
};

export async function signSession(payload: SessionPayload): Promise<string> {
  return new SignJWT({ mid: payload.mid, gid: payload.gid, sec: payload.sec })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuedAt()
    .setIssuer(ISSUER)
    .setAudience(AUDIENCE)
    .setExpirationTime(`${SESSION_TTL_SEC}s`)
    .sign(getKey());
}

export async function verifySession(
  token: string,
): Promise<SessionPayload | null> {
  try {
    const { payload } = await jwtVerify(token, getKey(), {
      algorithms: ["HS256"],
      issuer: ISSUER,
      audience: AUDIENCE,
    });
    if (
      typeof payload.mid !== "string" ||
      typeof payload.gid !== "string" ||
      typeof payload.sec !== "string"
    ) {
      return null;
    }
    return { mid: payload.mid, gid: payload.gid, sec: payload.sec };
  } catch {
    return null;
  }
}

export const SESSION_COOKIE_NAME = SESSION_COOKIE;
export const SESSION_TTL = SESSION_TTL_SEC;

export const sessionCookieOptions = {
  name: SESSION_COOKIE,
  httpOnly: true,
  sameSite: "lax" as const,
  secure: process.env.NODE_ENV === "production",
  path: "/",
};
